name: Bug Report
description: 버그 리포트 템플릿
title: "[Bug] "
labels: ["type:bug"]
body:
  - type: textarea
    id: content
    attributes:
      label: Bug Details
      description: 아래 템플릿 전체를 한 번에 복붙해서 작성하세요.
      value: |
        ## Summary
        - 버그 요약

        ## Steps To Reproduce
        1. ...
        2. ...
        3. ...

        ## Expected Result
        - 기대 결과

        ## Actual Result
        - 실제 결과

        ## Logs / Evidence
        - 에러 로그, 스크린샷, 요청/응답

        ## Severity
        - critical / major / minor

        ## Environment
        - local docker / branch / commit
    validations:
      required: true
