name: Bug Report
description: 버그 리포트 템플릿
title: "[Bug] "
labels: ["type:bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: 버그를 한 줄로 요약하세요.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps To Reproduce
      description: 재현 절차를 번호로 작성하세요.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Result
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Result
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / Evidence
      description: 에러 로그, 스크린샷, 요청/응답 예시 첨부
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - critical
        - major
        - minor
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      placeholder: local docker / branch / commit
