name: Feature Request
description: 기능 개발 이슈 템플릿
title: "[Feature] "
labels: ["type:feature"]
body:
  - type: textarea
    id: content
    attributes:
      label: Feature Details
      description: 아래 템플릿 전체를 한 번에 복붙해서 작성하세요.
      value: |
        ## Background
        - 왜 필요한 기능인지

        ## Goal
        - 완료 조건(DoD)

        ## Scope
        - include:
        - exclude:

        ## Technical Notes
        - 설계/제약/트레이드오프

        ## Test Plan
        - 단위/통합/부하 테스트 계획

        ## Target Date
        - YYYY-MM-DD
    validations:
      required: true
