name: Tech Debt
description: 기술 부채 개선 템플릿
title: "[TechDebt] "
labels: ["type:techdebt"]
body:
  - type: textarea
    id: content
    attributes:
      label: Tech Debt Details
      description: 아래 템플릿 전체를 한 번에 복붙해서 작성하세요.
      value: |
        ## Debt Description
        - 어떤 기술 부채인지

        ## Impact
        - 현재 리스크
        - 미래 리스크

        ## Proposed Solution
        - 개선 방안
        - 대안/트레이드오프

        ## Acceptance Criteria
        - [ ] 완료 조건 1
        - [ ] 완료 조건 2
    validations:
      required: true
